[tools]
rust = "stable"

[tasks.build]
description = "Build the forensic imager in release mode"
run = "cargo build --release"

[tasks.run]
description = "Run the forensic imager in release mode (Prompts for Admin)"
depends = ["build"]
run = "powershell -Command \"Start-Process -FilePath '.\\target\\release\\forgelens-disk-imager.exe' -Verb RunAs\""

[tasks.commit]
description = "Commit changes to git"
run = "git add . && git commit -m 'issue-resolved'"

[tasks.push]
description = "Push changes to git"
depends = ["commit"]
run = "git push"
